In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [5]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [13]:
# creates an empty 2x3 array with garbage values
emptyArr = np.empty((2,3))
print(emptyArr)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [1.95819673e-306 1.89146896e-307 7.56571288e-307]]


In [14]:
# Creates a 2x3 array with value 7
arr3 = np.full((2,3),7)
print(arr3)

[[7 7 7]
 [7 7 7]]


In [21]:
arr4 = np.array([1,2,4,3,5,3,2,1,3,4])
counts = np.bincount(arr4)          # each index in the counts array represents the frequency of that element in the given array
print(counts)

[0 2 2 3 2 1]


In [22]:
maxi = np.argmax(arr4)         # returns index of max value in the array
print(maxi)

4


In [30]:
# Count the number of non-zero values in the array
arr5 = np.array([1,2,4,0,3,0,2,3,50,0])
nonZero = np.count_nonzero(arr5)
print(nonZero)

7


In [33]:
# Reverse the numpy array
arr6 = np.array([1,2,3,4,5])
reversedArr = arr6[::-1]
print(reversedArr)

[5 4 3 2 1]


In [34]:
# Replace negative value with zero in numpy array
arr7 = np.array([1,2,-1,-5,0,3,-9])
arr7[arr7<0] = 0
print(arr7)

[1 2 0 0 0 3 0]


In [35]:
# Get the floor values of the elements in array
arr8 = [1.23, 3.54, 9.23, 10.213]
floorValues = np.floor(arr8)
print(floorValues)

[ 1.  3.  9. 10.]


In [37]:
# Get the ceil valeus of all the elements in array
arr9 = [1.23, 3.54, 9.23, 10.213]
ceilValues = np.ceil(arr9)
print(ceilValues)

[ 2.  4. 10. 11.]


In [38]:
# Get the truncated values of the elements in array
arr10 = [1.23, 3.54, 9.23, 10.213]
truncatedValues = np.trunc(arr10)
print(truncatedValues)

[ 1.  3.  9. 10.]
