# Welcome to numpy tutorial

In [3]:
import numpy as np

In [13]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)

[[1 2 3 4]
 [5 6 7 8]]


In [14]:
arr2 = np.array([2,4,6,8], np.int8)        # the second argument provides the type of integer (here we have given an 8 bit integer)
print(arr2)

[2 4 6 8]


In [15]:
arr1.shape            # provides the shape of array means the nubmer of rows and columns

(2, 4)

In [16]:
arr2.shape

(4,)

In [22]:
# we can also change the element
arr1[0, 3] = 100
print(arr1)

arr2[3] = 100
print(arr2)

[[  1   2   3 100]
 [  5   6   7   8]]
[  2   4   6 100]


## Conversion from other Python structures

In [26]:
# creating array from list
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(listarray)
print("Datatype: ",listarray.dtype)
print("Shape: ",listarray.shape)
print("Size: ",listarray.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Datatype:  int32
Shape:  (3, 3)
Size:  9


In [31]:
# creating array from dictionary
arr1 = np.array({22,23,25})
print(arr1)

{25, 22, 23}


In [34]:
# creating a zero array
zeroArray = np.zeros((2,5))
print(zeroArray)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [36]:
# creating an array in range
rng = np.arange(15)
print(rng)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [39]:
lspace1 = np.linspace(1,6,4)      # gives 4 elements between 1 and 6 which are equally spaced
print(lspace1)

lspace2 = np.linspace(1,4,4)
print(lspace2)

[1.         2.66666667 4.33333333 6.        ]
[1. 2. 3. 4.]


In [42]:
# creating an empty array
emp = np.empty((3, 4))                  # the default value can be any garbage value
print(emp)

[[1.15184944e-311 2.81617418e-322 0.00000000e+000 0.00000000e+000]
 [1.11260619e-306 2.46567317e+179 5.20764663e-090 5.73900956e+174]
 [1.52533325e-052 2.85471530e-056 6.48224660e+170 4.93432906e+257]]


In [43]:
# identity matrix
ide = np.identity(5)          # gives an identity matrix of size 5x5
print(ide)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [48]:
# Reshape the size of array
arr1 = np.arange(10)       # gives an array of values from 0 to 9
arr1.reshape(2, 5)         # returns the reshaped array but it will not affect arr1
# arr1.reshape(3,4)          # not allowed as the number of elements must be equal 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [49]:
# To convert a multidimensional array to 1D array
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)
np.ravel(arr2)            # returns the elements in linear order

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Numpy axis